# Conclusion

Through the training of the models SVM, Decision Tree, KNN, and Lasso, a supervised regression model was created that was able to give accurate predictions on future earnings 6 years post-graduation. The model that proved most effective at getting results closest to the true values was the SVM model, which reported an R-squared of about 0.8 and an RMSE of 4527. Of all the predictions that the SVM model made, 80% of them were within about $5,000 of the true reported earnings, and nearly 50% were within $2,000. Correlations between features were also discovered, many of which had to do with the financial situation students were in and how that effected their outcome at these institutions.

These results show that it is possible to explain the data and provide meaningful results to the end user. Since the goal of this project is to create a tool that can guide students to picking an institution that fits their goals, the results of the model provided a good estimation that can be used by these students to guide their decisions. Although the RMSE was around $4,500 its impact on the project as a whole is not as significant. Since the data is predicting earnings that are typically in the range of tens of thousands of dollars, being off by about $4,500 is not as much of a problem because the results of the model are just for educational purposes and guiding future students decisions. It would be impossible to provide a model that perfectly predicts what a student can expect to earn after graduating, that being said it is still possible to create a model that provides a very good image of what the future might look like, and that is what this project has been able to do.

Although the results were acceptable, there are still things that need to be improved upon in future works, the first major area of improvement is the interpretability of the model. The model used around 80 features to train the data which makes it hard to understand the impact of each one, and since the model was non-linear the significance of each feature was not possible to determine. Another future area of research is better pre-processing of the data. Looking at the fit of the different models compared to the true values, there were clear patterns that all models seemed to follow. This would indicate that there may be some factor that was not being accounted for in the training process.